### PR TITLE
Add FastAPI integration

### PR DESCRIPTION
**Pull request by hynek**
So I've done this mostly blindly by trawling the FastAPI docs… it would be great if some FastAPI expert could give me feedback if this makes conceptually sense, or if I've got something fundamentally wrong. @tiangolo maybe? 😇

### CODE REVIEW

**Comment by michaeloliverx** [comment]
Maybe the FastAPI expert himself @Kludex?

**Comment by hynek** [comment]
Every FastAPI expert is welcome; I'm not in the know enough to @ spam them all 🐶 💛

**Comment by Kludex** [comment]
@michaeloliverx used "the" because I advertise myself as such: https://www.fastapiexpert.com/

I can take a look tonight.

**Comment by hynek** [comment]
Awesome thanks!

**Comment by tiangolo** [comment]
And @Kludex IS the current top official FastAPI Expert: https://fastapi.tiangolo.com/fastapi-people/#experts 😎

**Comment by tiangolo** [comment]
I haven't used svcs, but checking mainly the examples they look great! I think it's all good from the FastAPI point of view.

One small thing I would do, mainly just syntax sugar, as  this seems like it would be a common pattern:

```Python
def do_stuff(
    svcs: Annotated[svcs.Container, Depends(svcs.fastapi.container)],
):
    ...
```

In `svcs.fastapi` I would also create/export a type alias with that, something like:

```Python
DepContainer = Annotated[svcs.Container, Depends(svcs.fastapi.container)]
```

And then in user's code they could do:

```Python
from svcs.fastapi import DepContainer

def do_stuff(
    svcs: DepContainer,
):
    ...
```

...one of the big reasons to support `Annotated` was to allow other tools (e.g. svcs) to do this trick and make users' code super simple. 🤓

I would maybe also comment in the docs that both things are equivalent. But just provide that type alias for extra niceness. ✨

**Comment by hynek** [comment]
> I haven't used svcs, 

Nobody has except me. 🤓 There's still a fat warning that every release is a breaking release and it's basically an internal project that I'm trying to make fit for the public.

And to make sure I don't paint myself into a corner, I'm trying to implement idiomatic integrations for all common web frameworks (starlette is next, but I believe it's just recycling of `svcs.fastapi.lifespan` plus a middleware or maybe just a `svcs_from`).

It's been a hectic month, but I'm starting to see the light at the end of the tunnel

> but checking mainly the examples they look great! I think it's all good from the FastAPI point of view.

Good to hear!

> One small thing I would do, mainly just syntax sugar, as this seems like it would be a common pattern:
> 
> ```python
> def do_stuff(
>     svcs: Annotated[svcs.Container, Depends(svcs.fastapi.container)],
> ):
>     ...
> ```
> 
> In `svcs.fastapi` I would also create/export a type alias with that, something like:
> 
> ```python
> DepContainer = Annotated[svcs.Container, Depends(svcs.fastapi.container)]
> ```
> 
> And then in user's code they could do:
> 
> ```python
> from svcs.fastapi import DepContainer
> 
> def do_stuff(
>     svcs: DepContainer,
> ):
>     ...
> ```
> 
> ...one of the big reasons to support `Annotated` was to allow other tools (e.g. svcs) to do this trick and make users' code super simple. 🤓
> 
> I would maybe also comment in the docs that both things are equivalent. But just provide that type alias for extra niceness. ✨

Ah that’s cool, this is exactly the feedback I’ve been hoping for – thank you so much!

**Pull request merged**
